## Operações Matemáticas Básicas

In [1]:
2 + 3

5

In [2]:
7 * 5

35

In [3]:
3.4 * 2.7

9.18

In [4]:
2.3 / 7

0.32857142857142857

In [5]:
2 + 3
4 + 5

9

In [6]:
3 ^ 5

243

In [7]:
3.0 ^ 5.0

243.0

In [8]:
2.3 ^ 3.4

16.977535312787566

In [9]:
exp(2)

7.38905609893065

In [10]:
log(3) # Logaritmo na base natural - ln

1.0986122886681098

In [11]:
log10(3)

0.47712125471966244

In [12]:
log10(2) + log10(5)

1.0

In [13]:
sin(0)

0.0

In [14]:
cos(0)

1.0

In [15]:
sin(30)

-0.9880316240928618

In [16]:
sind(30)

0.5

In [17]:
sin(3.14 / 6)

0.4997701026431024

In [18]:
pi

π = 3.1415926535897...

In [19]:
sin(pi / 6)

0.49999999999999994

In [20]:
exp(1)

2.718281828459045

In [21]:
MathConstants.e

ℯ = 2.7182818284590...

In [22]:
log(MathConstants.e)

1

In [23]:
π

π = 3.1415926535897...

In [25]:
α = 2.5

2.5

In [26]:
α ^ 2

6.25

In [27]:
x = 3

3

In [28]:
batata = 7

7

In [29]:
batata ^ x

343

In [30]:
"batata"

"batata"

In [32]:
"batata " * "frita"

"batata frita"

In [35]:
2 + 3

5

In [36]:
ans

5

In [81]:
sqrt(ans + 1)

1.618033988749895

## Álgebra Linear Numérica

In [82]:
v = [1.0; 2.0; 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [83]:
v + v

3-element Array{Float64,1}:
 2.0
 4.0
 6.0

In [84]:
v * 2

3-element Array{Float64,1}:
 2.0
 4.0
 6.0

In [85]:
w = [3.0; -1.0; 2.0]

3-element Array{Float64,1}:
  3.0
 -1.0
  2.0

In [86]:
v + w

3-element Array{Float64,1}:
 4.0
 1.0
 5.0

In [87]:
2 * v + 3 * w

3-element Array{Float64,1}:
 11.0
  1.0
 12.0

In [88]:
A = [5.0  4.0  -2.0; 1.0 2.0 3.0]

2×3 Array{Float64,2}:
 5.0  4.0  -2.0
 1.0  2.0   3.0

In [89]:
A * v

2-element Array{Float64,1}:
  7.0
 14.0

In [90]:
A'

3×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
  5.0  1.0
  4.0  2.0
 -2.0  3.0

In [91]:
transpose(A)

3×2 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
  5.0  1.0
  4.0  2.0
 -2.0  3.0

In [92]:
adjoint(A)

3×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
  5.0  1.0
  4.0  2.0
 -2.0  3.0

In [93]:
B = ones(2, 3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [95]:
C = A + im * B

2×3 Array{Complex{Float64},2}:
 5.0+1.0im  4.0+1.0im  -2.0+1.0im
 1.0+1.0im  2.0+1.0im   3.0+1.0im

In [96]:
transpose(C)

3×2 LinearAlgebra.Transpose{Complex{Float64},Array{Complex{Float64},2}}:
  5.0+1.0im  1.0+1.0im
  4.0+1.0im  2.0+1.0im
 -2.0+1.0im  3.0+1.0im

In [97]:
adjoint(C)

3×2 LinearAlgebra.Adjoint{Complex{Float64},Array{Complex{Float64},2}}:
  5.0-1.0im  1.0-1.0im
  4.0-1.0im  2.0-1.0im
 -2.0-1.0im  3.0-1.0im

In [98]:
using LinearAlgebra

In [99]:
dot(v, w) # produto interno

7.0

In [100]:
norm(v)

3.7416573867739413

In [101]:
A = [4.0 1.0; 2.0 3.0]

2×2 Array{Float64,2}:
 4.0  1.0
 2.0  3.0

In [102]:
b = [6.0; 8.0]

2-element Array{Float64,1}:
 6.0
 8.0

In [103]:
x = A \ b

2-element Array{Float64,1}:
 1.0
 2.0

In [104]:
A * x - b

2-element Array{Float64,1}:
 0.0
 0.0

In [106]:
Λ, V = eigen(A)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
2-element Array{Float64,1}:
 2.0
 5.0
vectors:
2×2 Array{Float64,2}:
 -0.447214  0.707107
  0.894427  0.707107

In [107]:
Λ

2-element Array{Float64,1}:
 2.0
 5.0

In [108]:
V

2×2 Array{Float64,2}:
 -0.447214  0.707107
  0.894427  0.707107

In [109]:
lu(A)

LU{Float64,Array{Float64,2}}
L factor:
2×2 Array{Float64,2}:
 1.0  0.0
 0.5  1.0
U factor:
2×2 Array{Float64,2}:
 4.0  1.0
 0.0  2.5

In [110]:
svd(A)

SVD{Float64,Float64,Array{Float64,2}}
U factor:
2×2 Array{Float64,2}:
 -0.767752  -0.640747
 -0.640747   0.767752
singular values:
2-element Array{Float64,1}:
 5.116672736016927
 1.9543950758485482
Vt factor:
2×2 Array{Float64,2}:
 -0.850651  -0.525731
 -0.525731   0.850651

In [111]:
qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
2×2 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.894427  -0.447214
 -0.447214   0.894427
R factor:
2×2 Array{Float64,2}:
 -4.47214  -2.23607
  0.0       2.23607

In [112]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [113]:
zeros(4, 5)

4×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [114]:
zeros(2, 3, 4)

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0
 0.0  0.0  0.0

In [115]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [116]:
ones(3, 4)

3×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [117]:
rand(3)

3-element Array{Float64,1}:
 0.3262334640841582
 0.38033050418657854
 0.770773985650977

In [118]:
rand(3, 4)

3×4 Array{Float64,2}:
 0.69065   0.437184  0.0672259  0.049077
 0.219806  0.514643  0.181803   0.947211
 0.382903  0.795515  0.361067   0.991482

In [119]:
randn(3)

3-element Array{Float64,1}:
 -1.0188905890373303
 -0.20840623111402867
  2.152717643911122

In [120]:
randn(100)

100-element Array{Float64,1}:
  0.560552603482908
 -0.1082164896579493
 -1.2442477708216875
 -0.35402833557547525
 -1.3972962685507093
 -1.223090922969845
  1.1143217972454407
  0.10340128573722465
 -0.7317153913049069
 -0.6488003506233215
 -0.859556233371449
 -1.5007960780511893
  0.40664431209370494
  ⋮
 -0.6675404718231552
  0.4088873276513968
 -0.27860078607626776
  0.0832999752946992
  0.351596160270315
 -0.40309814611255085
  2.098776608281898
  0.2568224730333291
  1.5981930821008643
 -0.9780642516891351
 -0.8627115741937137
 -2.229541387280022

In [121]:
v

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [122]:
w

3-element Array{Float64,1}:
  3.0
 -1.0
  2.0

In [123]:
[v; w]

6-element Array{Float64,1}:
  1.0
  2.0
  3.0
  3.0
 -1.0
  2.0

In [124]:
[v  w]

3×2 Array{Float64,2}:
 1.0   3.0
 2.0  -1.0
 3.0   2.0

In [125]:
[v'; w']

2×3 Array{Float64,2}:
 1.0   2.0  3.0
 3.0  -1.0  2.0

In [126]:
A

2×2 Array{Float64,2}:
 4.0  1.0
 2.0  3.0

In [128]:
[A; v w]

5×2 Array{Float64,2}:
 4.0   1.0
 2.0   3.0
 1.0   3.0
 2.0  -1.0
 3.0   2.0

In [130]:
[rand(3, 3)  ones(3, 2);  zeros(2, 3)  I]

5×5 Array{Float64,2}:
 0.29344   0.250977  0.338548  1.0  1.0
 0.186909  0.171844  0.738783  1.0  1.0
 0.595496  0.991799  0.150543  1.0  1.0
 0.0       0.0       0.0       1.0  0.0
 0.0       0.0       0.0       0.0  1.0

In [134]:
I * A * I + I

2×2 Array{Float64,2}:
 5.0  1.0
 2.0  4.0

In [135]:
I

UniformScaling{Bool}
true*I

In [137]:
Matrix(1.0I, 3, 4)

3×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0

In [163]:
v

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [164]:
v[1]

1.0

In [165]:
w[1]

3.0

In [166]:
dot(v, w)

7.0

In [167]:
v[1] * w[1] + v[2] * w[2] + v[3] * w[3]

7.0

In [171]:
A[1,2]

1.0

In [170]:
A

2×2 Array{Float64,2}:
 4.0  1.0
 2.0  3.0

In [177]:
A[2]

2.0

In [173]:
A[2][2]

BoundsError: BoundsError

In [178]:
:

(::Colon) (generic function with 14 methods)

In [179]:
A[:,2]

2-element Array{Float64,1}:
 1.0
 3.0

In [181]:
A[1,:]

2-element Array{Float64,1}:
 4.0
 1.0

In [180]:
A

2×2 Array{Float64,2}:
 4.0  1.0
 2.0  3.0

In [182]:
A = rand(5, 5)

5×5 Array{Float64,2}:
 0.103556  0.110333  0.104948  0.15855   0.345555
 0.593463  0.955599  0.513516  0.270503  0.0850543
 0.999511  0.502641  0.126613  0.648695  0.94325
 0.746026  0.998886  0.345777  0.94136   0.321235
 0.807941  0.342773  0.307355  0.423869  0.396046

In [184]:
A[2:5, 2:4]

4×3 Array{Float64,2}:
 0.955599  0.513516  0.270503
 0.502641  0.126613  0.648695
 0.998886  0.345777  0.94136
 0.342773  0.307355  0.423869

In [185]:
v[1:2]

2-element Array{Float64,1}:
 1.0
 2.0

## Funções

In [154]:
f(x) = x^2 - 3x

f (generic function with 1 method)

In [139]:
f(2)

2

In [140]:
g(x) = sqrt(x^2 + 1), 2x + 1

g (generic function with 1 method)

In [142]:
valor = g(2)

(2.23606797749979, 5)

In [143]:
valor[1]

2.23606797749979

In [144]:
valor[2]

5

In [145]:
a, b = g(2)

(2.23606797749979, 5)

In [146]:
a

2.23606797749979

In [147]:
b

5

In [148]:
h(x, y, z) = x * y * z

h (generic function with 1 method)

In [149]:
h(2, 3, 4)

24

In [150]:
f(2)

2

In [151]:
f(2.0)

2.0

In [152]:
A

2×2 Array{Float64,2}:
 4.0  1.0
 2.0  3.0

In [156]:
f(A) # A^2 - 3A

2×2 Array{Float64,2}:
 6.0  4.0
 8.0  2.0

In [157]:
A * A - 3 * A

2×2 Array{Float64,2}:
 6.0  4.0
 8.0  2.0

In [158]:
f("batata")

MethodError: MethodError: no method matching *(::Int64, ::String)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  *(!Matched::Missing, ::AbstractString) at missing.jl:174
  *(::T, !Matched::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  ...

In [161]:
function bhaskara(a, b, c)
    Δ = b^2 - 4 * a * c
    x1 = (-b + sqrt(Δ)) / 2a
    x2 = (-b - sqrt(Δ)) / 2a
    return x1, x2
end

bhaskara (generic function with 1 method)

In [162]:
bhaskara(1.0, -4.0, 3.0)

(3.0, 1.0)

In [189]:
função = x -> log(x^2 + 1)

#7 (generic function with 1 method)

In [190]:
função(3)

2.302585092994046

$$ f'(x) = \lim_{h \to 0} \frac{f(x + h) - f(x)}{h} $$

In [191]:
function derivada(f, x, h) # diferença finita
    (f(x + h) - f(x)) / h
end

derivada (generic function with 1 method)

In [193]:
f # x^2 - 3x

f (generic function with 1 method)

In [198]:
1e-8 # 10^-8

1.0e-8

In [199]:
derivada(f, 2.0, 1e-8)

0.999999993922529

In [201]:
derivada(x -> log(x^2 + 1), 2.0, 1e-8)

0.7999999995789153

In [202]:
function derivada2(f, x, h = 1e-8)
    (f(x + h) - f(x)) / h
end

derivada2 (generic function with 2 methods)

In [206]:
derivada2(x -> log(x^2 + 1), 2.0)

0.7999999995789153

In [207]:
function derivada3(f, x; h = 1e-8)
    (f(x + h) - f(x)) / h
end

derivada3 (generic function with 1 method)

In [208]:
derivada3(x -> log(x^2 + 1), 2.0)

0.7999999995789153

In [213]:
derivada3(x -> log(x^2 + 1), 2.0, 1e-2)

MethodError: MethodError: no method matching derivada3(::var"#34#35", ::Float64, ::Float64)
Closest candidates are:
  derivada3(::Any, ::Any; h) at In[207]:1

In [214]:
derivada3(x -> log(x^2 + 1), 2.0, h = 1e-2)

0.7988010722182581

## Tipos

In [215]:
1

1

In [216]:
1.0

1.0

In [217]:
v[1]

1.0

In [218]:
v[1.0]

ArgumentError: ArgumentError: invalid index: 1.0 of type Float64

In [219]:
v[6/2]

ArgumentError: ArgumentError: invalid index: 3.0 of type Float64

In [220]:
6/2

3.0

In [221]:
div(6, 2)

3

In [222]:
div(5, 2)

2

In [223]:
Any

Any

In [224]:
Float64, Int, Complex, AbstractFloat, Integer, Real, Number

(Float64, Int64, Complex, AbstractFloat, Integer, Real, Number)

In [225]:
[2, 3]

2-element Array{Int64,1}:
 2
 3

In [226]:
[2.0, 3.0]

2-element Array{Float64,1}:
 2.0
 3.0

In [227]:
[2, 3.0]

2-element Array{Float64,1}:
 2.0
 3.0

In [228]:
[2, 3.0, 1.0im]

3-element Array{Complex{Float64},1}:
 2.0 + 0.0im
 3.0 + 0.0im
 0.0 + 1.0im

In [229]:
Number[2, 3.0, 1.0im]

3-element Array{Number,1}:
     2
     3.0
 0.0 + 1.0im

In [230]:
Any[2, 3.0, 1.0im]

3-element Array{Any,1}:
     2
     3.0
 0.0 + 1.0im

In [231]:
Real[2, 3.0, 1.0im]

InexactError: InexactError: Real(0.0 + 1.0im)

In [232]:
["a", "b"]

2-element Array{String,1}:
 "a"
 "b"

In [234]:
L = ["a", "b", 3]

3-element Array{Any,1}:
  "a"
  "b"
 3

In [235]:
push!(L, π)

4-element Array{Any,1}:
  "a"
  "b"
 3
 π = 3.1415926535897...

In [236]:
L

4-element Array{Any,1}:
  "a"
  "b"
 3
 π = 3.1415926535897...

In [237]:
L = [L; 0.0]

5-element Array{Any,1}:
  "a"
  "b"
 3
 π = 3.1415926535897...
 0.0

In [238]:
push

UndefVarError: UndefVarError: push not defined

In [239]:
push!

push! (generic function with 26 methods)

In [240]:
Bool

Bool

In [241]:
true, false

(true, false)

In [242]:
Symbol

Symbol

In [243]:
:sucesso

:sucesso

In [244]:
:falha

:falha

In [245]:
Function

Function

In [246]:
f

f (generic function with 1 method)

In [247]:
function derivada4(f, x::Real, h::Real = 1e-8)
    (f(x + h) - f(x)) / h
end

derivada4 (generic function with 2 methods)

In [248]:
derivada4(f, "batata")

MethodError: MethodError: no method matching derivada4(::typeof(f), ::String)
Closest candidates are:
  derivada4(::Any, !Matched::Real) at In[247]:1
  derivada4(::Any, !Matched::Real, !Matched::Real) at In[247]:1

In [249]:
derivada2(f, "batata")

MethodError: MethodError: no method matching +(::String, ::Float64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::Missing, ::Number) at missing.jl:115
  +(!Matched::Bool, ::T) where T<:AbstractFloat at bool.jl:103
  ...

In [250]:
function fatorial(n::Int)
end

fatorial (generic function with 1 method)

In [287]:
w

3-element Array{Float64,1}:
  3.0
 -1.0
  2.0

In [288]:
exp(w)

MethodError: MethodError: no method matching exp(::Array{Float64,1})
Closest candidates are:
  exp(!Matched::Float16) at math.jl:1144
  exp(!Matched::Missing) at math.jl:1197
  exp(!Matched::Complex{Float16}) at math.jl:1145
  ...

In [289]:
exp.(w)

3-element Array{Float64,1}:
 20.085536923187668
  0.36787944117144233
  7.38905609893065

In [290]:
w + 1

MethodError: MethodError: no method matching +(::Array{Float64,1}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::Missing, ::Number) at missing.jl:115
  +(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:116
  ...

In [291]:
w .+ 1

3-element Array{Float64,1}:
 4.0
 0.0
 3.0

In [292]:
v .* w

3-element Array{Float64,1}:
  3.0
 -2.0
  6.0

In [293]:
A

5×5 Array{Float64,2}:
 0.103556  0.110333  0.104948  0.15855   0.345555
 0.593463  0.955599  0.513516  0.270503  0.0850543
 0.999511  0.502641  0.126613  0.648695  0.94325
 0.746026  0.998886  0.345777  0.94136   0.321235
 0.807941  0.342773  0.307355  0.423869  0.396046

In [294]:
exp.(A)

5×5 Array{Float64,2}:
 1.10911  1.11665  1.11065  1.17181  1.41277
 1.81025  2.60023  1.67116  1.31062  1.08878
 2.71695  1.65308  1.13498  1.91304  2.56831
 2.1086   2.71525  1.41309  2.56347  1.37883
 2.24328  1.40885  1.35982  1.52786  1.48594

In [296]:
derivada2.(x -> x^2 + 1, [-1, 0, 1])

3-element Array{Float64,1}:
 -1.999999987845058
  0.0
  1.999999987845058

In [297]:
v ./ w

3-element Array{Float64,1}:
  0.3333333333333333
 -2.0
  1.5

## Ranges e listas compactas

In [259]:
v[1:2]

2-element Array{Float64,1}:
 1.0
 2.0

In [260]:
1:2

1:2

In [261]:
3:100

3:100

In [262]:
collect(3:6)

4-element Array{Int64,1}:
 3
 4
 5
 6

In [263]:
collect(3:100)

98-element Array{Int64,1}:
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
  14
  15
   ⋮
  89
  90
  91
  92
  93
  94
  95
  96
  97
  98
  99
 100

In [264]:
2:0.1:3

2.0:0.1:3.0

In [265]:
collect(2:0.1:3)

11-element Array{Float64,1}:
 2.0
 2.1
 2.2
 2.3
 2.4
 2.5
 2.6
 2.7
 2.8
 2.9
 3.0

In [266]:
0:π / 4:2π

0.0:0.7853981633974483:6.283185307179586

In [267]:
collect(0:π / 4:2π)

9-element Array{Float64,1}:
 0.0
 0.7853981633974483
 1.5707963267948966
 2.356194490192345
 3.141592653589793
 3.9269908169872414
 4.71238898038469
 5.497787143782138
 6.283185307179586

In [268]:
range(0, 2π, length=100)

0.0:0.06346651825433926:6.283185307179586

## Laço for

In [269]:
# Para cada elemento do conjunto
# Faça alguma coisa

In [270]:
# Para cada elemento x no conjunto 1:5, println(x).
for x in 1:5
    println(x)
end

1
2
3
4
5


In [271]:
for x = 1:5
    println(x)
end

1
2
3
4
5


In [272]:
for x = 1:5
    print(x)
end

12345

In [273]:
for x in 0:0.1:1
    println(x ^ 2)
end

0.0
0.010000000000000002
0.04000000000000001
0.09
0.16000000000000003
0.25
0.36
0.48999999999999994
0.6400000000000001
0.81
1.0


In [274]:
v, w

([1.0, 2.0, 3.0], [3.0, -1.0, 2.0])

In [275]:
n = length(v)

3

In [276]:
function produto_interno(v, w)
    n = length(v)
    S = 0.0
    for i = 1:n
        S = S + v[i] * w[i] # S ← S + vᵢ wᵢ
    end
    return S
end

produto_interno (generic function with 1 method)

In [277]:
produto_interno(v, w)

7.0

In [278]:
v, w

([1.0, 2.0, 3.0], [3.0, -1.0, 2.0])

In [281]:
for vi in v, wi in w
    println("vi = $vi, wi = $wi") # $vi quer dizer valor de vi na string
end

vi = 1.0, wi = 3.0
vi = 1.0, wi = -1.0
vi = 1.0, wi = 2.0
vi = 2.0, wi = 3.0
vi = 2.0, wi = -1.0
vi = 2.0, wi = 2.0
vi = 3.0, wi = 3.0
vi = 3.0, wi = -1.0
vi = 3.0, wi = 2.0


In [282]:
for (vi, wi) in zip(v, w)
    println("vi = $vi, wi = $wi") # $vi quer dizer valor de vi na string
end

vi = 1.0, wi = 3.0
vi = 2.0, wi = -1.0
vi = 3.0, wi = 2.0


In [284]:
using Printf

for (vi, wi) in zip(v, w)
    println("π * vi / wi = $(π * vi / wi)") # $(...) quer dizer valor de tudo dentro (...)
    @printf("π * vi / wi = %5.3lf\n", π * vi / wi)
end

π * vi / wi = 1.0471975511965976
π * vi / wi = 1.047
π * vi / wi = -6.283185307179586
π * vi / wi = -6.283
π * vi / wi = 4.71238898038469
π * vi / wi = 4.712


In [285]:
z = zeros(3)
for i = 1:3
    z[i] = v[i]^2 * w[i] + 1
end

In [286]:
z

3-element Array{Float64,1}:
  4.0
 -3.0
 19.0

In [298]:
v .^ 2 .* w .+ 1

3-element Array{Float64,1}:
  4.0
 -3.0
 19.0

In [299]:
function fatorial(n :: Int) # n! = n * (n - 1)! = n * (n - 1) * … * 1
    resultado = 1
    for i = 1:n
        resultado = resultado * i
    end
    return resultado
end

fatorial (generic function with 1 method)

In [300]:
fatorial(5)

120

In [301]:
fatorial(0)

1

In [302]:
fatorial(-1)

1

In [303]:
fatorial(2.5)

MethodError: MethodError: no method matching fatorial(::Float64)
Closest candidates are:
  fatorial(!Matched::Int64) at In[299]:1

## Condicional

In [304]:
# Se alguma coisa, então
# Faça algo
# Senão, se outra coisa, então
# Faça outro algo
# Senão, caso contrário
# Faça um último algo
# FIM

In [305]:
function sinal(x)
    if x > 0
        return 1
    elseif x < 0
        return -1
    else
        return 0
    end
end

sinal (generic function with 1 method)

In [307]:
sinal(2.3), sinal(-1.0), sinal(0)

(1, -1, 0)

In [308]:
sinal.(-1:0.25:1)

9-element Array{Int64,1}:
 -1
 -1
 -1
 -1
  0
  1
  1
  1
  1

In [310]:
x = 8
if x > 1
    println("x > 1")
elseif x > 6
    println("x > 6")
end

x > 1


In [311]:
function fatorial(n :: Int) # n! = n * (n - 1)! = n * (n - 1) * … * 1
    if n < 0
        error("Não existe fatorial para n < 0")
    end
    resultado = 1
    for i = 1:n
        resultado = resultado * i
    end
    return resultado
end

fatorial (generic function with 1 method)

In [312]:
fatorial(-1)

ErrorException: Não existe fatorial para n < 0

In [313]:
fatorial(10)

3628800

**Exercício:** Refaça a função de Bhaskara. Se $\Delta < 0$, dê um erro. Se $\Delta = 0$, retorne um único número. Senão, faça o normal.

In [ ]:
function bhaskara ...

In [314]:
bhaskara(1, 0, 1)

DomainError: DomainError with -4.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [318]:
bhaskara(1, 4, 4)

(-2.0, -2.0)

## Laço while

In [319]:
# Enquanto uma condição for satisfeito
# Repita passos

In [320]:
function maior_potencia(x :: Int) # 1, 2, 4, 8, 16, 
    if x < 1
        error("Aí não")
    end
    p = 1
    while p * 2 ≤ x # Se eu dobrar o p, continua ≤ x?
        p = 2p # Se sim, dobre o p, e repita
    end
    return p
end

maior_potencia (generic function with 1 method)

In [321]:
maior_potencia(10)

8

In [322]:
maior_potencia(8)

8

In [324]:
maior_potencia(7)

4

In [325]:
for n = [1, 10, 100, 1000, 10000, 100000, 1000000]
    p = maior_potencia(n)
    println("2ᵏ = p ≤ n, n = $n, p = $p")
end

2ᵏ = p ≤ n, n = 1, p = 1
2ᵏ = p ≤ n, n = 10, p = 8
2ᵏ = p ≤ n, n = 100, p = 64
2ᵏ = p ≤ n, n = 1000, p = 512
2ᵏ = p ≤ n, n = 10000, p = 8192
2ᵏ = p ≤ n, n = 100000, p = 65536
2ᵏ = p ≤ n, n = 1000000, p = 524288


In [327]:
# Dado n > 1 qualquer
# Se n = 1, FIM
# Se n é par, n ← n / 2
# Se n é ímpar, n ← 3n + 1

In [328]:
n = 3

3

In [329]:
n % 2 # Resto da divisão por 2

1

In [342]:
if n % 2 == 0 # == quer dizer comparação da igualdade. É diferente do =
    n = div(n, 2)
else
    n = 3n + 1
end
n

1

In [347]:
function collatz(n)
    k = 0
    while n != 1
        if n % 2 == 0 # == quer dizer comparação da igualdade. É diferente do =
            n = div(n, 2)
        else
            n = 3n + 1
        end
        k = k + 1
    end
    return k
end

collatz (generic function with 1 method)

In [349]:
collatz(100)

25

In [350]:
# MMC(a, b) é o mínimo múltiplo em comum

In [351]:
function mmc(a :: Int, b :: Int)
    if a < 1 || b < 1 # || quer dizer ou
        error("mmc só para naturais positivos")
    end
    xa, xb = a, b
    println("xa = $xa, xb = $xb")
    while xa != xb
        if xa < xb
            xa = xa + a
        else
            xb = xb + b
        end
        println("xa = $xa, xb = $xb")
    end
    return xa
end

mmc (generic function with 1 method)

In [352]:
mmc(2, 3)

xa = 2, xb = 3
xa = 4, xb = 3
xa = 4, xb = 6
xa = 6, xb = 6


6

In [353]:
mmc(4, 6)

xa = 4, xb = 6
xa = 8, xb = 6
xa = 8, xb = 12
xa = 12, xb = 12


12

In [354]:
mmc(15, 12)

xa = 15, xb = 12
xa = 15, xb = 24
xa = 30, xb = 24
xa = 30, xb = 36
xa = 45, xb = 36
xa = 45, xb = 48
xa = 60, xb = 48
xa = 60, xb = 60


60

## Dicionários

In [359]:
D = Dict(
    "tudo" => "ok",
    "e aí" => "beleza",
    "top" => "top"
)

Dict{String,String} with 3 entries:
  "tudo" => "ok"
  "e aí" => "beleza"
  "top"  => "top"

In [360]:
D["tudo"]

"ok"

In [361]:
D["e aí"]

"beleza"

In [362]:
D["top"]

"top"

## Estruturas

In [363]:
struct Retangulo
    x :: Float64
    y :: Float64
    θ :: Float64
    w :: Float64
    h :: Float64
end

In [365]:
R = Retangulo(0, 0, π / 6, 2.0, 1.0)

Retangulo(0.0, 0.0, 0.5235987755982988, 2.0, 1.0)

In [366]:
function area(R :: Retangulo)
    return R.w * R.h
end

area (generic function with 1 method)

In [367]:
area(R)

2.0