In [1]:
A = rand(3, 5)
B = rand(5, 4)
A * B

3×4 Array{Float64,2}:
 1.44762   0.894008  0.911667  1.2092
 0.994353  1.26291   0.891858  1.06659
 1.70265   1.32967   1.33819   1.87497

In [2]:
C = zeros(3, 4)
for i = 1:3, j = 1:4
    C[i,j] = sum(A[i,k] * B[k,j] for k = 1:5)
end
C

3×4 Array{Float64,2}:
 1.44762   0.894008  0.911667  1.2092
 0.994353  1.26291   0.891858  1.06659
 1.70265   1.32967   1.33819   1.87497

In [3]:
n = 100000
Float64.size * (3n - 2) / 1024 / 1024, Float64.size * n^2 / 1024 / 1024

(2.2888031005859375, 76293.9453125)

In [4]:
using Pkg
pkg"add BenchmarkTools"

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]


In [5]:
using BenchmarkTools

In [6]:
function multAx1(y, A, x)
    m, n = size(A)
    for i = 1:m
        y[i] = 0.0
        for j = 1:n
            y[i] += A[i,j] * x[j]
        end
    end
end

function multAx2(y, A, x)
    m, n = size(A)
    for i = 1:m
        y[i] = 0.0
    end
    for j = 1:n
        for i = 1:m
            y[i] += A[i,j] * x[j]
        end
    end
end

multAx2 (generic function with 1 method)

In [7]:
n = 1000
A = rand(n, n)
x = rand(n);

In [8]:
y1 = zeros(n)
y2 = zeros(n)
multAx1(y1, A, x)
multAx2(y2, A, x)
y1 ≈ y2 ≈ A * x

true

In [9]:
y = zeros(n)
@benchmark multAx1(y, $A, $x)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     2.199 ms (0.00% GC)
  median time:      2.541 ms (0.00% GC)
  mean time:        2.775 ms (0.00% GC)
  maximum time:     5.911 ms (0.00% GC)
  --------------
  samples:          1795
  evals/sample:     1

In [10]:
y = zeros(n)
@benchmark multAx2(y, $A, $x)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     945.833 μs (0.00% GC)
  median time:      1.047 ms (0.00% GC)
  mean time:        1.111 ms (0.00% GC)
  maximum time:     2.204 ms (0.00% GC)
  --------------
  samples:          4463
  evals/sample:     1

In [11]:
using SparseArrays

In [12]:
A = sprand(10, 10, 0.3)

10×10 SparseMatrixCSC{Float64,Int64} with 29 stored entries:
  [2 ,  1]  =  0.272204
  [3 ,  1]  =  0.538193
  [4 ,  1]  =  0.8676
  [6 ,  1]  =  0.155929
  [7 ,  1]  =  0.458494
  [10,  1]  =  0.19625
  [6 ,  2]  =  0.743521
  [2 ,  3]  =  0.967841
  [4 ,  3]  =  0.808462
  [9 ,  3]  =  0.575446
  [3 ,  4]  =  0.782049
  [6 ,  4]  =  0.273989
  ⋮
  [7 ,  6]  =  0.28218
  [3 ,  7]  =  0.0203452
  [6 ,  7]  =  0.849862
  [9 ,  7]  =  0.725731
  [10,  7]  =  0.0637224
  [8 ,  8]  =  0.140144
  [9 ,  8]  =  0.378408
  [10,  8]  =  0.936851
  [5 ,  9]  =  0.191336
  [1 , 10]  =  0.918424
  [5 , 10]  =  0.81676
  [6 , 10]  =  0.520414
  [8 , 10]  =  0.690414

In [13]:
rows, cols, vals = findnz(A)

([2, 3, 4, 6, 7, 10, 6, 2, 4, 9  …  9, 10, 8, 9, 10, 5, 1, 5, 6, 8], [1, 1, 1, 1, 1, 1, 2, 3, 3, 3  …  7, 7, 8, 8, 8, 9, 10, 10, 10, 10], [0.27220404249229113, 0.5381932261464486, 0.8676000977093936, 0.15592882284476395, 0.4584936174993044, 0.19625012549346477, 0.7435207308493004, 0.967841220254837, 0.8084618246737303, 0.5754461698689874  …  0.7257307883220614, 0.06372238707347733, 0.1401438236056518, 0.3784078579849557, 0.9368508224327796, 0.191336319337986, 0.9184235530142997, 0.8167596346576891, 0.5204142285368252, 0.690413796111665])

**Exercício:** Fazer as 6 ordens da $C = AB$.

## Sistemas Lineares

In [14]:
A = rand(3, 3)
b = A * ones(3)

3-element Array{Float64,1}:
 1.9579530105129408
 2.1834026175682215
 2.304759235850707

In [15]:
A \ b # Resolve Ax = b

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [16]:
A = [3.0 1 2; -1 2 1; 1 1 4]

3×3 Array{Float64,2}:
  3.0  1.0  2.0
 -1.0  2.0  1.0
  1.0  1.0  4.0

In [17]:
b = A * ones(3)

3-element Array{Float64,1}:
 6.0
 2.0
 6.0

In [18]:
m21 = A[2,1] / A[1,1]
m31 = A[3,1] / A[1,1]

# L₂ = A[2,:], L₃ = A[3,:]
A[2,2:end] = A[2,2:end] - m21 * A[1,2:end]
A[2,1] = 0.0
A[3,2:end] = A[3,2:end] - m31 * A[1,2:end]
A[3,1] = 0.0

0.0

In [19]:
b[2] = b[2] - m21 * b[1]
b[3] = b[3] - m31 * b[1]

4.0

In [20]:
A

3×3 Array{Float64,2}:
 3.0  1.0       2.0
 0.0  2.33333   1.66667
 0.0  0.666667  3.33333

In [21]:
b

3-element Array{Float64,1}:
 6.0
 4.0
 4.0

In [22]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999999

In [23]:
m32 = A[3,2] / A[2,2]
A[3,3:end] -= m32 * A[2,3:end]
A[3,2] = 0.0
b[3] -= m32 * b[2]

A

3×3 Array{Float64,2}:
 3.0  1.0      2.0
 0.0  2.33333  1.66667
 0.0  0.0      2.85714

In [24]:
b

3-element Array{Float64,1}:
 6.0
 4.0
 2.8571428571428568

In [25]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999998

In [26]:
"""
    elim_gauss!(A, b)

Modifica A e b fazendo a eliminação Gaussiana.
"""
function elim_gauss!(A, b)
    m, n = size(A)
    for j = 1:n
        cols = j+1:n
        for i = j+1:m
            mij = A[i,j] / A[j,j]
            A[i,cols] -= mij * A[j,cols]
            A[i,j] = 0.0
            b[i] -= mij * b[j]
        end
    end
end

elim_gauss!

In [27]:
A = rand(5, 5)
#A[:,3] = A[:,2] + 2 * A[:,5]
b = A * ones(5)

5-element Array{Float64,1}:
 2.8179490402932243
 2.7476279299633446
 1.9655119432293024
 3.3283849343875618
 2.2080627625461773

In [28]:
A

5×5 Array{Float64,2}:
 0.35633    0.704142  0.548019   0.932386  0.277072
 0.455423   0.950434  0.631336   0.199955  0.51048
 0.0743427  0.288895  0.87586    0.656925  0.0694897
 0.96058    0.23544   0.468875   0.745122  0.918367
 0.127134   0.789274  0.0476764  0.311853  0.932125

In [29]:
elim_gauss!(A, b)

In [30]:
A

5×5 Array{Float64,2}:
 0.35633  0.704142    0.548019     0.932386   0.277072
 0.0      0.0504755  -0.0690831   -0.991721   0.156357
 0.0      0.0         0.955854     3.2521    -0.428147
 0.0      0.0         0.0        -23.2637     3.85107
 0.0      0.0         0.0          0.0        0.845247

In [31]:
b

5-element Array{Float64,1}:
   2.8179490402932243
  -0.853972431080102
   3.7798087757733825
 -19.41267045920594
   0.8452471711112128

In [32]:
A \ b

5-element Array{Float64,1}:
 0.9999999999999978
 1.000000000000002
 1.0000000000000013
 0.9999999999999992
 0.9999999999999982

In [34]:
function resolve_tri_sup(U, c) # Ux = c
    m, n = size(U)
    if m != n
        error("Dimensões de U devem ser iguais")
    end
    x = zeros(n)
    for j = n:-1:1
        # xⱼ = (bⱼ - ∑ₖ₌ⱼ₊₁ⁿ uⱼₖ xₖ ) / uⱼⱼ
        x[j] = b[j]
        for k = j+1:n
            x[j] -= U[j,k] * x[k]
        end
        x[j] = x[j] / U[j,j]
    end
    return x
end

resolve_tri_sup (generic function with 1 method)

In [35]:
resolve_tri_sup(A, b)

5-element Array{Float64,1}:
 1.000000000000001
 0.9999999999999994
 1.0000000000000018
 0.9999999999999991
 0.9999999999999981

In [36]:
"""
    elim_gauss!(A)

Modifica A fazendo a eliminação Gaussiana e guardando mᵢⱼ.
Só para matrizes quadrados.
"""
function elim_gauss!(A)
    m, n = size(A)
    if m != n
        error("Dimensões de A devem ser iguais")
    end
    for j = 1:n
        cols = j+1:n
        for i = j+1:n
            mij = A[i,j] / A[j,j]
            A[i,cols] -= mij * A[j,cols]
            A[i,j] = mij
        end
    end
end

elim_gauss!

In [37]:
"""
    aplica_gauss_em_b!(A, b)

Faz a eliminação Gaussiana em b usando os mᵢⱼ guardados em A.
"""
function aplica_gauss_em_b!(A, b)
    m, n = size(A)
    if m != n
        error("Dimensões de A devem ser iguais")
    end
    for j = 1:n
        for i = j+1:n
            mij = A[i,j]
            b[i] -= mij * b[j]
        end
    end
end

aplica_gauss_em_b!

In [54]:
A = rand(5, 5)
b = A * ones(5)
borig = copy(b)

5-element Array{Float64,1}:
 2.4024951498598033
 0.9843566793677092
 2.4583553333020745
 2.5542563802845066
 2.5756630703631056

In [55]:
elim_gauss!(A)

In [56]:
A

5×5 Array{Float64,2}:
 0.680135  0.18241    0.835742    0.63255     0.0716576
 0.323015  0.202769  -0.0715903  -0.0578755   0.135011
 1.39858   2.98695   -0.951518   -0.252242   -0.320193
 0.778123  3.8432     0.355667    0.309598    0.116649
 0.447603  0.660669  -0.229387    1.26222     0.475079

In [57]:
aplica_gauss_em_b!(A, b)

In [58]:
b

5-element Array{Float64,1}:
  2.4024951498598033
  0.20831375476827618
 -1.523953711534381
  0.4262477700943291
  0.47507936275238083

In [59]:
resolve_tri_sup(A, b)

5-element Array{Float64,1}:
 0.9999999999999993
 1.0000000000000004
 0.9999999999999997
 1.0000000000000016
 0.9999999999999991

In [60]:
A * ones(5) - borig # A não pode ser usada diretamente mais

5-element Array{Float64,1}:
  0.0
 -0.4530275276090504
  0.4032228872535244
  2.8489817440685146
  0.040516677217706576

In [61]:
A = [0.0 1.0; 1.0 0.0]
b = A * ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [62]:
elim_gauss!(A)

In [63]:
A

2×2 Array{Float64,2}:
  0.0    1.0
 Inf   -Inf

In [75]:
ϵ = 1e-12
A = [ϵ 100; 1 ϵ]
b = A * ones(2)

elim_gauss!(A)
aplica_gauss_em_b!(A, b)
x = resolve_tri_sup(A, b)

2-element Array{Float64,1}:
 0.9947598300641403
 1.0

In [71]:
ϵ = 1e-12
A = [1 ϵ; ϵ 100]
b = A * ones(2)

elim_gauss!(A)
aplica_gauss_em_b!(A, b)
resolve_tri_sup(A, b)

2-element Array{Float64,1}:
 1.0
 1.0

In [74]:
ϵ - 100 / ϵ == -100 / ϵ

true

In [148]:
A = rand(3, 3)
b = A * ones(3)

3-element Array{Float64,1}:
 1.1661128356615558
 1.5435688751015244
 2.2099173314415927

In [149]:
A

3×3 Array{Float64,2}:
 0.648606  0.00516242  0.512345
 0.351231  0.995832    0.196506
 0.763158  0.681334    0.765426

In [150]:
# Eliminar coluna 1
j = 1
k = argmax(abs.(A[:,j]))
A[ [j, k], :] = A[ [k, j], :]
b[ [j, k] ] = b[ [k, j] ]

2-element Array{Float64,1}:
 2.2099173314415927
 1.1661128356615558

In [151]:
m21 = A[2,1] / A[1,1]
m31 = A[3,1] / A[1,1]
A[2,:] -= A[1,:] * m21
A[3,:] -= A[1,:] * m31
b[2] -= m21 * b[1]
b[3] -= m31 * b[1]

-0.7120894103318514

In [152]:
A

3×3 Array{Float64,2}:
 0.763158   0.681334   0.765426
 0.0        0.682259  -0.155769
 0.0       -0.573901  -0.138188

In [153]:
# Eliminar coluna 2
j = 2
k = argmax(abs.(A[j:end,j])) + j - 1
if k != j
    A[ [j, k], :] = A[ [k, j], :]
    b[ [j, k] ] = b[ [k, j] ]
end

In [154]:
m32 = A[3,2] / A[2,2]
A[3,:] -= A[2,:] * m32
b[3] -= m32 * b[2]

-0.2692180903351308

In [155]:
A

3×3 Array{Float64,2}:
 0.763158  0.681334   0.765426
 0.0       0.682259  -0.155769
 0.0       0.0       -0.269218

In [156]:
b

3-element Array{Float64,1}:
  2.2099173314415927
  0.5264895849529283
 -0.2692180903351308

In [157]:
A \ b

3-element Array{Float64,1}:
 1.0000000000000002
 1.0
 0.9999999999999996

In [159]:
"""
    elim_gauss_pivo!(A, b)

Modifica A e b fazendo a eliminação Gaussiana.
"""
function elim_gauss_pivo!(A, b)
    m, n = size(A)
    for j = 1:n
        cols = j+1:n
        k = argmax(abs.(A[j:n,j])) + j - 1
        if k != j
            A[ [j, k], :] = A[ [k, j], :]
            b[ [j, k] ] = b[ [k, j] ]
        end
        for i = j+1:m
            mij = A[i,j] / A[j,j]
            A[i,cols] -= mij * A[j,cols]
            A[i,j] = 0.0
            b[i] -= mij * b[j]
        end
    end
end

elim_gauss_pivo!

In [161]:
A = rand(10, 10)
b = A * ones(10)
elim_gauss_pivo!(A, b)
resolve_tri_sup(A, b)

10-element Array{Float64,1}:
 1.000000000000003
 1.0000000000000009
 0.9999999999999997
 1.0000000000000004
 1.0000000000000018
 1.0000000000000004
 1.0000000000000002
 0.9999999999999982
 0.9999999999999987
 0.9999999999999979

In [165]:
using LinearAlgebra

n = 10
A = Matrix(1.0I, n, n)
A[1,:] .= 1
A[:,1] .= 1
A[1,1] = n
Aorig = copy(A)
A

10×10 Array{Float64,2}:
 10.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [166]:
elim_gauss!(A)

In [167]:
A

10×10 Array{Float64,2}:
 10.0   1.0        1.0        1.0       …   1.0        1.0        1.0
  0.1   0.9       -0.1       -0.1          -0.1       -0.1       -0.1
  0.1  -0.111111   0.888889  -0.111111     -0.111111  -0.111111  -0.111111
  0.1  -0.111111  -0.125      0.875        -0.125     -0.125     -0.125
  0.1  -0.111111  -0.125     -0.142857     -0.142857  -0.142857  -0.142857
  0.1  -0.111111  -0.125     -0.142857  …  -0.166667  -0.166667  -0.166667
  0.1  -0.111111  -0.125     -0.142857     -0.2       -0.2       -0.2
  0.1  -0.111111  -0.125     -0.142857      0.75      -0.25      -0.25
  0.1  -0.111111  -0.125     -0.142857     -0.333333   0.666667  -0.333333
  0.1  -0.111111  -0.125     -0.142857     -0.333333  -0.5        0.5

In [169]:
A = copy(Aorig)
A[[1,n],:] = A[[n,1],:]
elim_gauss!(A)
triu(A)

10×10 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  -1.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  -1.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  -1.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  -1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  -1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  -1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  -1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  -1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  -1.0

In [172]:
tril(A, -1)

10×10 Array{Float64,2}:
  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 10.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0

In [173]:
A = copy(Aorig)
A[[1,n],:] = A[[n,1],:]
A[:,[1,n]] = A[:,[n,1]]
elim_gauss!(A)
triu(A)

10×10 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [174]:
tril(A,-1)

10×10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0